# Generated by Django 5.0.6 on 2024-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_pickedword_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickedDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pickedword',
            name='definition',
        ),
    ]
